blueprint:
  name: Door Sensor activated Light
  description: Turn on a light when a door is open after sun is below horizon.
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
  input:
    door_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    close_wait:
      name: Wait time
      description: Time to leave the light on after door is closed.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input door_entity
  from: "closed"
  to: "open"

condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there door is closed"
    wait_for_trigger:
      platform: state
      entity_id: !input door_entity
      from: "open"
      to: "closed"
  - alias: "Wait the number of seconds that has been set"
    delay: !input close_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
